global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'mysqld-exporter1'
    static_configs:
      - targets: ['host.docker.internal:30000']

  - job_name: 'mysqld-exporter2'
    static_configs:
      - targets: ['host.docker.internal:30001']
  - job_name : 'kakfa-exporter'
    static_configs:
      - targets: ['host.docker.internal:30002']
