spring:
  application:
    name: subscribe-service

  # Kafka Setting
  kafka:
    consumer:
      bootstrap-servers: localhost:9092


# MySQL Setting
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/subscribe_service_db?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
    username: root
    password: root

# JPA Setting
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate.hibernate.format_sql: true
    open-in-view: false

# Logging Setting
logging:
  level:
    org.springframework.transaction.interceptor: TRACE
    org.springframework.jdbc.datasource.DataSourceTransactionManager: DEBUG
    org.springframework.orm.jpa.JpaTransactionManager: DEBUG
    org.hibernate.resource.transaction: DEBUG
    org.hibernate.SQL: DEBUG

# Server Port Setting
server:
  port: 8082